-- Recall's original Supabase schema, now owned by the Recall repository.
--
-- Provenance: section 3 ("Supabase schema (final DDL)") of the archived
-- Anki-management/ANKI_WEB_PLAN.md that was used to create the anki-review
-- project. The table/column shapes, indexes, updated_at trigger, and RLS policy
-- are preserved. The CREATE/DROP forms are made idempotent, objects are schema
-- qualified, authenticated grants are explicit, and review_log preserves the
-- established single-owner default because app/RPC inserts omit user_id.
--
-- Apply first. This file is additive for an existing correctly-shaped project:
-- CREATE TABLE IF NOT EXISTS does not rewrite tables or rows. Verification is
-- deliberately separate and fails closed if an existing table has drifted.

begin;

-- Importer writes; authenticated app reads.
create table if not exists public.decks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  deck_id bigint not null,
  name text not null,
  deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, deck_id)
);

-- Importer writes; authenticated app reads.
create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  guid text not null,
  deck_id bigint not null,
  mid bigint not null,
  front text not null,
  back text not null,
  tags text not null default '',
  has_latex boolean not null default false,
  latex_svg jsonb,
  deleted boolean not null default false,
  anki_mod bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, guid)
);

create index if not exists idx_notes_user_deck
  on public.notes (user_id, deck_id)
  where deleted = false;

-- Importer seeds unseen cards; Recall owns scheduling after cloud_seen=true.
create table if not exists public.cards (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  note_id bigint not null references public.notes(id) on delete cascade,
  guid text not null,
  stability real not null default 0,
  difficulty real not null default 0,
  due timestamptz,
  state smallint not null default 0,
  reps integer not null default 0,
  lapses integer not null default 0,
  last_review timestamptz,
  cloud_seen boolean not null default false,
  deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, guid)
);

create index if not exists idx_cards_user_due
  on public.cards (user_id, due)
  where deleted = false;

create index if not exists idx_cards_user_state
  on public.cards (user_id, state)
  where deleted = false;

-- Append-only except Recall's explicit single-level undo delete.
create table if not exists public.review_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null default 'a0000000-0000-4000-8000-000000000001'::uuid
    references auth.users(id) on delete cascade,
  card_id bigint not null references public.cards(id) on delete cascade,
  guid text not null,
  rating smallint not null,
  rating_at timestamptz not null,
  stability_after real,
  difficulty_after real,
  due_after timestamptz,
  state_after smallint,
  elapsed_ms integer,
  device text,
  created_at timestamptz not null default now()
);

create index if not exists idx_review_log_user_date
  on public.review_log (user_id, rating_at desc);

-- JSON values currently use settings_key='fsrs_params' and 'recall_prefs'.
create table if not exists public.user_settings (
  id integer generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  settings_key text not null,
  settings_value jsonb not null,
  updated_at timestamptz not null default now(),
  unique (user_id, settings_key)
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists t_decks on public.decks;
create trigger t_decks
before update on public.decks
for each row execute function public.touch_updated_at();

drop trigger if exists t_notes on public.notes;
create trigger t_notes
before update on public.notes
for each row execute function public.touch_updated_at();

drop trigger if exists t_cards on public.cards;
create trigger t_cards
before update on public.cards
for each row execute function public.touch_updated_at();

drop trigger if exists t_settings on public.user_settings;
create trigger t_settings
before update on public.user_settings
for each row execute function public.touch_updated_at();

alter table public.decks enable row level security;
alter table public.notes enable row level security;
alter table public.cards enable row level security;
alter table public.review_log enable row level security;
alter table public.user_settings enable row level security;

drop policy if exists own on public.decks;
create policy own on public.decks for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists own on public.notes;
create policy own on public.notes for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists own on public.cards;
create policy own on public.cards for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists own on public.review_log;
create policy own on public.review_log for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists own on public.user_settings;
create policy own on public.user_settings for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

grant select on table public.decks, public.notes to authenticated;
grant select, update on table public.cards to authenticated;
grant select, insert, delete on table public.review_log to authenticated;
grant select, insert, update, delete on table public.user_settings to authenticated;
grant usage, select on sequence public.review_log_id_seq,
  public.user_settings_id_seq to authenticated;

commit;
