-- note_flags: review-time card feedback from Recall.
--
-- Provenance: copied from the deployed private runtime migration
-- recall-anki-sync/migrations/001_note_flags.sql. The live reason and status
-- sets, resolution fields, foreign keys, partial open-queue index, and RLS
-- policy are preserved. Idempotent DDL and explicit grants were added here.

begin;

create table if not exists public.note_flags (
  id bigint generated by default as identity primary key,
  user_id uuid not null default 'a0000000-0000-4000-8000-000000000001'::uuid
    references auth.users(id) on delete cascade,
  card_id bigint not null references public.cards(id) on delete cascade,
  guid text not null,
  reason text not null
    constraint note_flags_reason_check
    check (reason in ('wrong', 'confusing', 'too_long', 'duplicate')),
  flagged_at timestamptz not null,
  device text,
  status text not null default 'open'
    constraint note_flags_status_check
    check (status in ('open', 'resolved', 'dismissed')),
  resolved_at timestamptz,
  resolution text,
  created_at timestamptz not null default now()
);

create index if not exists idx_note_flags_open
  on public.note_flags (user_id, status)
  where status = 'open';

alter table public.note_flags enable row level security;

drop policy if exists own on public.note_flags;
create policy own on public.note_flags for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

grant select, insert, update on table public.note_flags to authenticated;
grant usage, select on sequence public.note_flags_id_seq to authenticated;

commit;
